### ISSUE TITLE
/usr/lib/libfontconfig.so.1: failed looking up symbol mkostemp

### ISSUE THREAD

**Issue by rowlandwatkins** [cloudius-systems/osv#684] opened 2015-11-24 13:49 UTC
Hi folks,

So I'm playing a little bit to see how much server side graphics I can do in Scala. AWT itself works fine (drawing, saving to disk), however I've hit a minor snag when drawing text:

OSv version: v0.22-1-gee3da4f
Java version: Oracle Server JRE 1.8.0_51

[[[
/usr/lib/libfontconfig.so.1: failed looking up symbol mkostemp

0x00000000003437ed <elf::object::symbol(unsigned int)+205>
0x0000000000345168 <elf::object::resolve_pltgot(unsigned int)+136>
0x0000000000345345 <elf_resolve_pltgot+69>
0x0000000000390dee <???+3739118>
0x0000200010ed412f <???+283984175>
0x63746e6f662f6567 <???+1714382183>
]]]

From what I can tell it appears to be having issues creating a unique temp file. Any tips?

Cheers,

Rowland

**Comment by nyh** [comment] 2015-11-24 13:55
This is a duplicate of #604. Please see #604 for something which might work, and it would be great if you could test that and send a patch if it works. Thanks!

**Closed by nyh** 2015-11-24 13:55 UTC
