### ISSUE TITLE
cloud-init: long pauses after "Probing EC2" and "Probing EC2"

### ISSUE THREAD

**Issue by vladzcloudius** [cloudius-systems/osv#457] opened 2014-08-17 09:53 UTC
It takes ages for these "Probing"s - more than 5 minutes each.

master HEAD: 36f78327bbde3815965420ac3b79feaec43b3310

**Comment by wkozaczuk** [comment] 2019-05-17 15:25
Is it still valid? Shall be closed?

**Comment by nyh** [comment] 2019-05-19 19:24
cloud-init changed a lot in the 5 years that passed since this issue was opened. It is likely it was already solved, or dependend on a sepcific configuration we can't reproduce now. So closing.

**Closed by nyh** 2019-05-19 19:24 UTC
Labels: obsolete
