### ISSUE TITLE
usr.img creation failure

### ISSUE THREAD

**Issue by rowlandwatkins** [cloudius-systems/osv#858] opened 2017-02-27 03:06 UTC
Hi folks,

Git revision: 8f0acb3aab1ee5308da198a2badaf1a6338f63e8

I do a daily build on our local CI, and got the following when the build script started uploading files (I don't think this is JVM-related):

[[[
<snip>
Adding /usr/lib/jvm/java/jre/lib/meta-index...
Adding /usr/lib/jvm/java/jre/lib/security/trusted.libraries...
Adding /usr/lib/jvm/java/lib/dt.jar...
Adding /usr/lib/jvm/java/jre/README...
Adding /usr/lib/jvm/java/jre/lib/fontconfig.bfc...
Adding /usr/lib/jvm/java/jre/lib/amd64/server/libjvm.so...
47240246960 < 85894895840, now=47240274140

[backtrace]
0x00000000003df770 <sched::timer_list::fired()+1120>
0x0000000000389e60 <interrupt_descriptor_table::invoke_interrupt(unsigned int)+192>
0x0000000000389fb2 <interrupt+130>
0x0000000000388e29 <???+3706409>
0x0000000000358c1a <virtio::vring::kick()+90>
0x000000000035b08c <???+3518604>
0x000000000024a6ae <ether_output+670>
0x0000000000266cf0 <ip_output(mbuf*, mbuf*, route*, int, ip_moptions*, inpcb*)+1584>
0x0000000000276908 <tcp_output+2664>
0x0000000000271a7f <???+2562687>
0x00000000002746db <???+2574043>
0x00000000004096d6 <net_channel::process_queue()+102>
0x000000000024021d <socket_file::poll(int)+45>
0x0000000000402866 <epoll_file::wait(epoll_event*, int, int)+1222>
0x00000000004008f0 <epoll_wait+112>
0x000010000201ff52 <boost::asio::detail::epoll_reactor::run(bool, boost::asio::detail::op_queue<boost::asio::detail::task_io_service_operation>&)+66>
0x00001000020225dd <???+33695197>
0x00000000005350ac <std::basic_streambuf<char, std::char_traits<char> >::xsgetn(char*, long)+188>
Traceback (most recent call last):
  File "/opt/jenkins/workspace/osv-daily/scripts/upload_manifest.py", line 215, in <module>
    main()
  File "/opt/jenkins/workspace/osv-daily/scripts/upload_manifest.py", line 207, in main
    upload(osv, manifest, depends)
  File "/opt/jenkins/workspace/osv-daily/scripts/upload_manifest.py", line 162, in upload
    cpio_send(f.read())
  File "/opt/jenkins/workspace/osv-daily/scripts/upload_manifest.py", line 96, in cpio_send
    s.sendall(data)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 104] Connection reset by peer
<snip>
]]]

I'll keep an eye out, this only started happening in the last 24 hours.

Cheers,

Rowland

**Comment by nyh** [comment] 2017-02-27 07:58
This is a duplicate of an, unfortunately, known bug - #382.
Many people have seen this bug, but unfortunately we don't know yet what is causing it. 
The only thing we know is that the backward clock jump is always - and also in your case - almost exactly - 38.6547 seconds, which is 9 * 2^32 nanoseconds. We still have no idea why, unfortunately, and I haven't been able to reliably reproduce this bug.

**Closed by nyh** 2017-02-27 07:58 UTC
