### ISSUE TITLE
Crash due to possible assertion in sched::timer_list::fired

### ISSUE THREAD

**Issue by wkozaczuk** [cloudius-systems/osv#831] opened 2017-01-12 12:48 UTC
This happened 3 times when playing with OSv image with httpserver running as an app.

OSv v0.24-251-gd415d67
eth0: 192.168.122.15
14005889302850 < 14044543057870, now=14005889324370

[backtrace]
0x00000000003df550 <sched::timer_list::fired()+1120>
0x0000000000389e90 <interrupt_descriptor_table::invoke_interrupt(unsigned int)+192>
0x0000000000389fe2 <interrupt+130>
0x0000000000388e59 <???+3706457>
0x00000000003e3767 <sched::cpu::idle()+39>
0x00000000003e378b <???+4077451>
0x00000000003e38c6 <thread_main_c+38>
0x0000000000388e82 <???+3706498>

**Comment by nyh** [comment] 2017-01-12 13:01
This is a duplicate of issue #382 which we unfortunately never solved, so let's move the discussion there.

Note that the backward jump of the clock in this message is 14044543057870-14005889302850 = 38653755020 nanoseconds, or 38.6538 seconds. This is suspiciously identical to the backward jump of 38 seconds we saw in issue #382. So there must be a reason for this specific backward jump of the clock... Anybody recognize what is magical about this amount of 38 seconds?

**Closed by nyh** 2017-01-12 13:01 UTC
