### ISSUE TITLE
debug build fails with "loader-stripped.elf is greater than 23068672, needed to uncompress kernel"

### ISSUE THREAD

**Issue by tijoytom** [cloudius-systems/osv#700] opened 2015-12-22 05:34 UTC
Seems to happen only with debug build..
tijoytom@patha:~/osv$ scripts/build -j4 mode=debug

Building into build/debug.x64
  GEN gen/include/osv/version.h
build/debug.x64/loader-stripped.elf is greater than 23068672, needed to uncompress kernel
Change arch/x64/boot16.S and arch/x65/lzloader.ld 
 in order to have more available space for the kernel. 
make: **\* [build/debug.x64/lzloader.elf] Error 1
make failed. Exiting from build script

**Comment by nyh** [comment] 2015-12-22 07:13
Can you please try "scripts/build clean" and then run scripts/build again?
I heard from someone this solved the same problem. I still don't know why it happens, but can you please try?

**Comment by nyh** [comment] 2015-12-22 07:14
(or rather, "scripts/build clean mode=debug").

**Comment by tijoytom** [comment] 2015-12-22 16:38
I believe i did "scripts/build clean mode=debug" first and then "scripts/build -j4 mode=debug". I will give it another try and report back.

**Comment by tijoytom** [comment] 2015-12-22 16:50
Same error ...

 LZ loader-stripped.elf
  OBJCOPY loader-stripped.elf.lz -> loader-stripped.elf.lz.o
build/debug.x64/loader-stripped.elf is greater than 23068672, needed to uncompress kernel
Change arch/x64/boot16.S and arch/x65/lzloader.ld 
 in order to have more available space for the kernel. 
make: *** [build/debug.x64/lzloader.elf] Error 1
make failed. Exiting from build script

**Comment by nyh** [comment] 2015-12-22 17:21
I cannot reproduce this problem, so I wonder if you can help me with some background information. Did you change anything in OSv?
What does scripts/osv-version.sh show?
What does /etc/issue show? 
What does "gcc --version" show?
What does "ls -l build/debug.x64/loader-stripped.elf" show?

Sorry about all these questions :-) Thanks.

**Comment by tijoytom** [comment] 2015-12-22 19:46
No , I haven't made any changes.

tijoytom@g:~/osv$ scripts/osv-version.sh
v0.24-34-g7a505f4

cat  /etc/issue
Ubuntu 14.04.3 LTS \n \l
gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4

-rwxrwxr-x 1 tijoytom tijoytom 23667072 Dec 22 08:46 build/debug.x64/loader-stripped.elf

**Comment by nyh** [comment] 2015-12-23 09:43
Ok, you're absolutely right. On my system (gcc 5.3.1), I have
-rwxr-xr-x. 1 nyh nyh 22283376 Dec 22 19:17 build/debug/loader-stripped.elf

So it's only a tiny bit smaller than the current maximum, and I am just lucky not to see it over the maximum - and you (or gcc 4.8.4) were just a little less lucky.

In a long comment towards the end of https://github.com/cloudius-systems/osv/issues/195 I explained in detail where this limit comes from. It can be enlarged by increasing the 0x1800000 in both arch/x64/lzloader.ld and arch/x64/boot16.S. It shouldn't be increased by a ridiculous amount or we'll also increase OSv's minimum memory requirement (as explained in the aforementioned comment). Can you please try if this indeed fixes your problem? Thanks.

It would be nice to have this parameter in a single place, and being able to easily increase it when needed. Also, we may want different numbers for the debug and release builds - as the release kernel is about half the size of the debug build. Perhaps we can even find the needed size automatically?

**Comment by tijoytom** [comment] 2015-12-24 00:10
OK , changing arch/x64/lzloader.ld and arch/x64/boot16.S and then the hard coded 23068672 in makefile and lzloader.cc  to be the new Y-X value fix the issue. 25MB seems to be reasonable for Debug , as you mentioned having a MAX_IMAGE_SIZE as build parameter for release and debug would be nice.I will see if I can add this MAX_IMAGE_SIZE( or whatever) once I am free

**Comment by nyh** [comment] 2017-04-27 14:02
I opened a new issue specifically on maing the kernel size limit easier to configure - issue #872.
So I'm closing this issue, as it's just one example of the more general problem.

**Closed by nyh** 2017-04-27 14:02 UTC
