### ISSUE TITLE
File locking not supported

### ISSUE THREAD

**Issue by penberg** [cloudius-systems/osv#67] opened 2013-10-23 11:58 UTC
File locking is not supported by the VFS.

Needed by DaCapo:

```
ACPI: All ACPI Tables successfully acquired








acpi 0 apic 0
acpi 1 apic 1
acpi 2 apic 2
acpi 3 apic 3
APIC base fee00000
OSv v0.01-296-g4ce131c Copyright 2013 Cloudius Systems
locale works
VFS: mounting ramfs at /
VFS: mounting devfs at /dev
ACPI: RSDP 0xfd8d0 00014 (v00 BOCHS )ACPI: RSDT 0xbfffe380 00034 (v01 BOCHS  BXPCRSDT 00000001 
BXPC 00000001)ACPI: FACP 0xbfffff80 00074 (v01 BOCHS  BXPCFACP 00000001 BXPC 00000001)ACPI: DSD
T 0xbfffe3c0 011A9 (v01   BXPC   BXDSDT 00000001 INTL 20100528)ACPI: FACS 0xbfffff40 00040ACPI:
 SSDT 0xbffff6e0 00858 (v01 BOCHS  BXPCSSDT 00000001 BXPC 00000001)ACPI: APIC 0xbffff5b0 00090 
(v01 BOCHS  BXPCAPIC 00000001 BXPC 00000001)ACPI: HPET 0xbffff570 00038 (v01 BOCHS  BXPCHPET 00
000001 BXPC 00000001)RAM disk at 0x3a80b000 (4096K bytes)
Initializing network stack...
Done!
eth0: ethernet address: 52:54:0:12:34:56
VFS: mounting zfs at /usr
zfs: mounting osv/usr from device /dev/vblk0.1
[I/38 dhcp]: Waiting for IP...
[I/329 dhcp]: Configuring eth0: ip 192.168.122.15 subnet mask 255.255.255.0 gateway 192.168.122
.1
[I/329 dhcp]: Server acknowledged IP for interface eth0
stub dlclose()
OpenJDK 64-Bit Server VM warning: Can't detect initial thread stack location - find_vma failed
device random not found
unsupported fcntl cmd 0x6
unsupported fcntl cmd 0x6
java.lang.IllegalStateException: Bundle initial@reference:file:plugins/org.eclipse.core.runtime_3.1.2.jar/ [1] is not active.
        at org.eclipse.core.runtime.adaptor.EclipseStarter.ensureBundlesActive(EclipseStarter.java:410)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:297)
        at dacapo.eclipse.EclipseHarness.startup(EclipseHarness.java:82)
        at dacapo.eclipse.EclipseHarness.preIteration(EclipseHarness.java:28)
        at dacapo.Benchmark.run(Benchmark.java:119)
        at dacapo.TestHarness.runBenchmark(TestHarness.java:283)
        at dacapo.TestHarness.main(TestHarness.java:242)
        at Harness.main(Harness.java:5)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at io.osv.RunJava.runMain(RunJava.java:153)
        at io.osv.RunJava$1.run(RunJava.java:124)
        at io.osv.OsvSystemClassLoader$1.run(OsvSystemClassLoader.java:40)
===== DaCapo eclipse starting warmup =====
java.lang.IllegalStateException: Platform not running
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:357)
        at dacapo.eclipse.EclipseHarness.iterate(EclipseHarness.java:35)
        at dacapo.Benchmark.run(Benchmark.java:126)
        at dacapo.TestHarness.runBenchmark(TestHarness.java:283)
        at dacapo.TestHarness.main(TestHarness.java:242)
        at Harness.main(Harness.java:5)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at io.osv.RunJava.runMain(RunJava.java:153)
        at io.osv.RunJava$1.run(RunJava.java:124)
        at io.osv.OsvSystemClassLoader$1.run(OsvSystemClassLoader.java:40)
Digest validation failed for stdout.log, expecting 0x3ccf21842a9962460ac4f7351108b50174b408e1 found 0xda39a3ee5e6b4b0d3255bfef95601890afd80709
Digest validation failed for stderr.log, expecting 0xda39a3ee5e6b4b0d3255bfef95601890afd80709 found 0x9c1e0503346c23aab586fbbe0ecab3c869bd704f
```

**Comment by nyh** [comment] 2016-04-07 10:34
The unsupported "fcntl cmd 0x6" is F_SETLK. This is a duplicate of #185

**Closed by nyh** 2016-04-07 10:34 UTC
