### ISSUE TITLE
Cassandra gets stuck when running ycsb workload-C

### ISSUE THREAD

**Issue by vladzcloudius** [cloudius-systems/osv#504] opened 2014-09-28 14:37 UTC
HEAD: cd046807b7b78b2560499025477f352683559ac0
How to reproduce: 
1) Build an image with cassandra: `make modules=cassandra`
2) Load an OSv with 16GB RAM and 4 vCPUs: `sudo scripts/run.py -m16G -c4 -nv`
3) Run the workload: 
   a) `./cass-load --init <OSv IP>`
   b) `for ((i=0;i<4;i++)); do ./cass-load 64 <OSv IP>; done`

Cassandra usually gets stuck at stage 3.a but sometimes at 3.b.
OSv always responds to pings and sometimes httpserver works,
however the terminal where OSv is running doesn't respond to keyboard. 
After qemu is killed with `sudo pkill qemu` and OSv is restarted we always see the ZFS error message like the one below:

```
Solaris: WARNING: ZFS replay transaction error 95, dataset osv/zfs, seq 0x1294ec, txtype 9 
```

cass-load script:

```
# !
# ! Usage: cass-load --init|<threads N> <server IP>
# !


###################################################################

function load()
{   
    echo "drop keyspace usertable;" | cassandra-cli -h $OSV
    cat > setup-ycsb.cql <<EOF
create keyspace usertable with placement_strategy = 'SimpleStrategy' and
strategy_options = {replication_factor:1};
use usertable;
create column family data with compression_options = null;
EOF 
    cassandra-cli -h $OSV -f setup-ycsb.cql
    ./bin/ycsb load cassandra-10 -threads 100 -p operationcount=100000 -p recordcount=800000 -p hosts=$OSV -P workloads/workloadc -s | tee load.log
}

function run()
{   
    ./bin/ycsb run cassandra-10 -threads $thrn -p operationcount=6000000 -p recordcount=800000 -p hosts=$OSV -P workloads/workloadc -s &> run.log
    grep "\[OVERALL\], Throughput(ops/sec)" run.log
}
####################################################################

if [[ $# -ne 2 ]]; then
        cat $0 | grep ^"# !" | cut -d"!" -f2-
        exit 1
fi


OSV=$2

if [[ $1 == "--init" ]]; then
        thrn=100
        load
        run
else
        thrn=$1
        run
fi
```

Run:

**Comment by wkozaczuk** [comment] 2021-06-30 20:51
The last comment by @raphaelsc suggests this bug was closed. Shall we close it?

**Comment by wkozaczuk** [comment] 2021-06-30 20:57
I think this issue was caused by the commit https://github.com/cloudius-systems/osv/commit/b5eadc37f12c4b97a52705830d2d9097498049c2 which was buggy and was reverted by https://github.com/cloudius-systems/osv/commit/697943f631960b3d55f66381581e1435b726a1a8. The latter specifically references this issue and seems to indicate that it fixed this deadlock. No?

**Closed** 2021-07-01 07:53 UTC
Labels: bug, high priority
