### ISSUE TITLE
Cassndra Cluster on EC2 disconnects when running cassandra-cli describe cluster command

### ISSUE THREAD

**Issue by slivne** [cloudius-systems/osv#537] opened 2014-10-28 21:10 UTC
The issue is only reproducible on EC2 - locally on XEN/KVM (using ec2-simulator.py) the issue does not happen.

How to reproduce:
1. Create a Cassandra AMI
2. Launch 2 instance specifying in the User Data:
   cassandra:
   clustername: Pekkas Cluster
   totalnodes: 2
3. After the instances have started connect to one of them with cassandra-cli (available under bin/cassandra-cli)
4. Execute "describe cluster"
   1. The command will either reuse open connection to the local/remote node or open new connections
- using default OpenJDK the behaviour is that the command gets stuck
- using OpenJDK 7.0.71 (java-1.7.0-openjdk-1.7.0.71-2.5.3.0.fc20.x86_64) causes an instance to report that node b is unreachable.
  - looking at /usr/cassandra/logs/system.log sometimes the following exception is shown:

```
java.net.SocketException: Network unreachable
        at sun.nio.ch.Net.connect0(Native Method) ~[na:1.7.0_71]
        at sun.nio.ch.Net.connect(Net.java:465) ~[na:1.7.0_71]
        at sun.nio.ch.Net.connect(Net.java:457) ~[na:1.7.0_71]
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:670) ~[na:1.7.0_71]
        at java.nio.channels.SocketChannel.open(SocketChannel.java:184) ~[na:1.7.0_71]
        at org.apache.cassandra.net.OutboundTcpConnectionPool.newSocket(OutboundTcpConnectionPool.java:134) ~[apache-cassandra-2.1.0.jar:2.1.0-SNAPSHOT]
        at org.apache.cassandra.net.OutboundTcpConnectionPool.newSocket(OutboundTcpConnectionPool.java:119) ~[apache-cassandra-2.1.0.jar:2.1.0-SNAPSHOT]
        at org.apache.cassandra.net.OutboundTcpConnection.connect(OutboundTcpConnection.java:356) [apache-cassandra-2.1.0.jar:2.1.0-SNAPSHOT]
        at org.apache.cassandra.net.OutboundTcpConnection.run(OutboundTcpConnection.java:168) [apache-cassandra-2.1.0.jar:2.1.0-SNAPSHOT]
DEBUG [ACCEPT-/10.97.150.16] 2014-10-26 14:11:19,366 MessagingService.java:930 - Connection version 7 from /10.97.150.16
```

Using the network tracing and downloading a PCAP file it can be seen that thhe local connection is openned (TCP SYN) yet the connection to the remote node is not openned (no TCP SYN sent)

**Comment by wkozaczuk** [comment] 2019-05-31 03:32
I do not think we can reproduce it. I suggest we close it.

**Comment by wkozaczuk** [comment] 2019-07-12 19:11
Given we cannot reproduce it and how little interest there is running Cassandra on OSv I am closing it.

**Closed by wkozaczuk** 2019-07-12 19:11 UTC
Labels: AWS, bug, high priority, wontfix
