### ISSUE TITLE
Can't run osv-memcached in osv

### ISSUE THREAD

**Issue by Answerhua** [cloudius-systems/osv#922] opened 2017-11-07 12:10 UTC
I tried to use "osv-memcached.so" in osv.
I tried to run it by:
sudo ./scripts/run.py -n -v -V -c1 -m4G -e "/tools/osv-memcached.so".

But it gave me some error.
/tools/osv-memcached.so: failed looking up symbol _ZN6memory8shrinkerC2ESs (memory::shrinker::shrinker(std::string))

[backtrace]
0x000000000033e133 <elf::object::symbol(unsigned int)+227>
0x0000000000340bc9 <elf::object::resolve_pltgot(unsigned int)+137>
0x0000000000340db5 <elf_resolve_pltgot+69>
0x00000000003878ef <???+3700975>
0x00002000001ffc7f <???+2096255>
0xfefefefefefefefe <???+-16843010>
0x6f6c2d6465686360 <???+1701340000>

Socket error Event: 32 Error: 10053.

I don't know, how could I solve this problem.

**Comment by nyh** [comment] 2017-11-07 15:32
I can reproduce this problem:
```
scripts/build image=osv-memcached
scripts/run.py
```
result is:
```
/tools/osv-memcached.so: failed looking up symbol _ZN6memory8shrinkerC2ESs (memory::shrinker::shrinker(std::string))
```

We do have a memory::shrinker::shrinker(std::string) as far as I can tell, so I think the error is due to recent C++ ABI changes in how std::string is represented (see also similar problems mentioned in issue #821) - nm in build/release/loader.elf yields that we don't have memory::shrinker::shrinker(std::string) but rather:
```
memory::shrinker::shrinker(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
```

What I still don't understand is how this happens in this case. I didn't find the "obvious" problems (like using -D_GLIBCXX_USE_CXX11_ABI=0 in osv-memcached's Makefile), so I don't know how this difference came to be. @vladzcloudius do you have any guesses?

By the way, please note that "osv-memcached" is not the ordinary memcached. It is an OSv-specific rewrite of memcached that doesn't have all the features of the original memcached. We also have the "memcached" package with the original memcached.

**Comment by Answerhua** [comment] 2017-11-09 11:33
Thank you maybe I would try some other images.

**Comment by wkozaczuk** [comment] 2021-07-12 04:05
Fixed by https://github.com/cloudius-systems/osv-apps/commit/6f5802d7468e41da1363386d2a8391cf6404dcfa

**Closed by wkozaczuk** 2021-07-12 04:05 UTC
