### ISSUE TITLE
Java error on attempting to log in to GitBucket

### ISSUE THREAD

**Issue by dmarti** [cloudius-systems/osv#318] opened 2014-05-25 03:50 UTC
This is on OSv v0.08-199-g6a29063 running with KVM (Fedora 20). Verified that this same WAR file with the same Tomcat run from the host allows logging in and clicking around.
- Get GitBucket 1.13 from: https://github.com/takezoe/gitbucket/releases
- Build and run OSv:  `make image=tomcat; sudo scripts/run.py -n -v`
- Go to the Tomcat page here: `http://192.168.122.89:8081/`
- Go to "Manager App" and upload GitBucket from the "WAR File to Deploy" section.
  Go to `http://192.168.122.89:8081/gitbucket/` and click the "Sign In" button at the upper right.

Error message:

```
HTTP Status 500 - Filter execution threw an exception

type Exception report

message Filter execution threw an exception

description The server encountered an internal error that prevented it from fulfilling this request.

exception

javax.servlet.ServletException: Filter execution threw an exception

root cause

org.h2.jdbc.JdbcSQLException: General error: "java.lang.ArrayIndexOutOfBoundsException: 2" [50000-173]
    org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
    org.h2.message.DbException.get(DbException.java:160)
    org.h2.message.DbException.convert(DbException.java:283)
    org.h2.engine.Database.openDatabase(Database.java:256)
    org.h2.engine.Database.<init>(Database.java:221)
    org.h2.engine.Engine.openSession(Engine.java:56)
    org.h2.engine.Engine.openSession(Engine.java:160)
    org.h2.engine.Engine.createSessionAndValidate(Engine.java:139)
    org.h2.engine.Engine.createSession(Engine.java:122)
    org.h2.engine.Engine.createSession(Engine.java:28)
    org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:313)
    org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:105)
    org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
    org.h2.Driver.connect(Driver.java:73)
    java.sql.DriverManager.getConnection(DriverManager.java:571)
    java.sql.DriverManager.getConnection(DriverManager.java:187)
    scala.slick.session.Database$$anon$2.createConnection(Database.scala:105)
    scala.slick.session.BaseSession.conn$lzycompute(Session.scala:207)
    scala.slick.session.BaseSession.conn(Session.scala:207)
    scala.slick.session.BaseSession.close(Session.scala:221)
    scala.slick.session.Database.withSession(Database.scala:38)
    scala.slick.session.Database.withSession(Database.scala:46)
    scala.slick.session.Database.withTransaction(Database.scala:58)
    servlet.TransactionFilter.doFilter(TransactionFilter.scala:23)

root cause

java.lang.ArrayIndexOutOfBoundsException: 2
    org.h2.store.PageStore.addMeta(PageStore.java:1678)
    org.h2.store.PageStore.readMetaData(PageStore.java:1594)
    org.h2.store.PageStore.recover(PageStore.java:1370)
    org.h2.store.PageStore.openExisting(PageStore.java:361)
    org.h2.store.PageStore.open(PageStore.java:285)
    org.h2.engine.Database.getPageStore(Database.java:2210)
    org.h2.engine.Database.open(Database.java:603)
    org.h2.engine.Database.openDatabase(Database.java:226)
    org.h2.engine.Database.<init>(Database.java:221)
    org.h2.engine.Engine.openSession(Engine.java:56)
    org.h2.engine.Engine.openSession(Engine.java:160)
    org.h2.engine.Engine.createSessionAndValidate(Engine.java:139)
    org.h2.engine.Engine.createSession(Engine.java:122)
    org.h2.engine.Engine.createSession(Engine.java:28)
    org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:313)
    org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:105)
    org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
    org.h2.Driver.connect(Driver.java:73)
    java.sql.DriverManager.getConnection(DriverManager.java:571)
    java.sql.DriverManager.getConnection(DriverManager.java:187)
    scala.slick.session.Database$$anon$2.createConnection(Database.scala:105)
    scala.slick.session.BaseSession.conn$lzycompute(Session.scala:207)
    scala.slick.session.BaseSession.conn(Session.scala:207)
    scala.slick.session.BaseSession.close(Session.scala:221)
    scala.slick.session.Database.withSession(Database.scala:38)
    scala.slick.session.Database.withSession(Database.scala:46)
    scala.slick.session.Database.withTransaction(Database.scala:58)
    servlet.TransactionFilter.doFilter(TransactionFilter.scala:23)

note The full stack trace of the root cause is available in the Apache Tomcat/7.0.42 logs.
Apache Tomcat/7.0.42
```

**Comment by wkozaczuk** [comment] 2019-05-17 14:49
Shall we close it? @penberg could not reproduce it as of 5 years ago :-)

**Comment by nyh** [comment] 2019-05-19 20:04
Yes, let's close this. Maybe it indicates an OSv bug, but nobody is going to run this ancient tomcat and specific WAR to try to reproduce this.

**Closed by nyh** 2019-05-19 20:04 UTC
Labels: bug, tomcat, wontfix
