### ISSUE TITLE
OSV image creation issue.

### ISSUE THREAD

**Issue by acsdkquery** [cloudius-systems/osv#899] opened 2017-07-27 09:22 UTC
OSV image creation fails. Trace following. 

seems the issue is with 'luasocket'. Kindly fix this.

out/bin/luarocks install luasocket 3.0-rc1
Warning: Failed searching manifest: Failed loading manifest: Failed extracting manifest file
Warning: Failed searching manifest: Failed loading manifest: Failed fetching manifest for http://luarocks.giga.puc-rio.br/ - Failed downloading http://luarocks.giga.puc-rio.br/manifest
Warning: Failed searching manifest: Failed loading manifest: Failed fetching manifest for http://luafr.org/luarocks/rocks - Failed downloading http://luafr.org/luarocks/rocks/manifest
Warning: Failed searching manifest: Failed loading manifest: Failed extracting manifest file
Warning: Failed searching manifest: Failed loading manifest: Failed extracting manifest file
Error: No results matching query were found.
Makefile:92: recipe for target 'out/lib/lua/5.2/socket/core.so' failed
make: *** [out/lib/lua/5.2/socket/core.so] Error 1
Using image config: /data/jenkins/jobs/osv_build/workspace/images/default.py
Importing /data/jenkins/jobs/osv_build/workspace/modules/cli/module.py
Importing /data/jenkins/jobs/osv_build/workspace/modules/lua/module.py
Importing /data/jenkins/jobs/osv_build/workspace/modules/ncurses/module.py
Importing /data/jenkins/jobs/osv_build/workspace/modules/libedit/module.py
Importing /data/jenkins/jobs/osv_build/workspace/modules/httpserver/module.py
Importing /data/jenkins/jobs/osv_build/workspace/modules/openssl/module.py
No module.py in /data/jenkins/jobs/osv_build/workspace/modules/libz
No module.py in /data/jenkins/jobs/osv_build/workspace/modules/libtools
No module.py in /data/jenkins/jobs/osv_build/workspace/modules/libyaml
Modules:
  lua
  ncurses
  libedit
  libz
  openssl
  libtools
  libyaml
  httpserver.*
  cli
Traceback (most recent call last):
  File "scripts/module.py", line 272, in <module>
    args.func(args)
  File "scripts/module.py", line 227, in build
    make_modules(modules, args)
  File "scripts/module.py", line 124, in make_modules
    raise Exception('make failed for ' + module.name)
Exception: make failed for lua
scripts/build failed: jdkbase=$jdkbase ARCH=$arch mode=$mode OSV_BASE=$SRC OSV_BUILD_PATH=$OSV_BUILD_PATH scripts/module.py $j_arg build -c $modules $usrskel_arg

**Comment by nyh** [comment] 2017-07-27 09:52
I can't reproduce this problem. I'm guessing that http://luarocks.giga.puc-rio.br is one of the luarocks mirrors, or something, and it has a problem? Can you please try again maybe it was a transient problem?

**Comment by acsdkquery** [comment] 2017-07-27 09:59
i am just cloning to the master branch and try building using jenkin, and i got this error.,

i tried again, same issue,

out/bin/luarocks install luasocket 3.0-rc1
Warning: Failed searching manifest: Failed loading manifest: Failed extracting manifest file

Warning: Failed searching manifest: Failed loading manifest: Failed fetching manifest for http://luarocks.giga.puc-rio.br/ - Failed downloading http://luarocks.giga.puc-rio.br/manifest

Warning: Failed searching manifest: Failed loading manifest: Failed fetching manifest for http://luafr.org/luarocks/rocks - Failed downloading http://luafr.org/luarocks/rocks/manifest
Warning: Failed searching manifest: Failed loading manifest: Failed extracting manifest file

Warning: Failed searching manifest: Failed loading manifest: Failed extracting manifest file

**Comment by nyh** [comment] 2017-07-27 10:17
I'm not familiar enough with luarocks to understand why it is trying those servers, and why they are not working.
Can you please try editing modules/lua/Makefile to edit the "out/bin/luarocks install luasocket 3.0-rc1" command to do "out/bin/luarocks install --server=http://luarocks.org luasocket 3.0-rc1" and see if it helps?

**Comment by acsdkquery** [comment] 2017-07-27 11:45
ok..issue is resolved by referring https://github.com/luarocks/luarocks/issues/238
Thanks for your time!

**Comment by nyh** [comment] 2017-07-27 11:56
So the problem was that your system was missing "unzip"?

**Comment by nyh** [comment] 2017-07-30 07:14
I'm guessing it was the missing "unzip" and closing this issue. Please reopen if it wasn't unzip.

Note that OSv depends on various additional development tools being installed on the build machine. We have a script, `scripts/setup.py`, which on several popular Linux distributions installs all the missing packages.

**Closed by nyh** 2017-07-30 07:14 UTC

**Comment by Myhat2you** [comment] 2019-01-27 14:41
I seem to also be getting this error message, however, I have all the dependencies for Ubuntu 18.04 installed through the setup.py script.
Any idea what the issue might be? Here's the output from trying to build it:

`Building into build/release.x64
  GEN gen/include/osv/version.h
Using image config: /home/hatter/osv/images/default.py
Importing /home/hatter/osv/modules/cli/module.py
Importing /home/hatter/osv/modules/lua/module.py
Importing /home/hatter/osv/modules/ncurses/module.py
Importing /home/hatter/osv/modules/libedit/module.py
Importing /home/hatter/osv/modules/httpserver/module.py
Importing /home/hatter/osv/modules/httpserver-html5-gui/module.py
Importing /home/hatter/osv/modules/httpserver-api/module.py
Importing /home/hatter/osv/modules/openssl/module.py
No module.py in /home/hatter/osv/modules/libz
No module.py in /home/hatter/osv/modules/libtools
No module.py in /home/hatter/osv/modules/libyaml
Modules:
  lua
  ncurses
  libedit
  libz
  openssl
  libtools
  libyaml
  httpserver-api
  httpserver-html5-gui
  httpserver.*
  cli
./check-openssl-version
OpenSSL 1.1 header detected.
On Fedora >= 26 please use the compat headers by doing:

    dnf install --allowerasing compat-openssl10-devel -y

Makefile:122: recipe for target 'out/share/lua/5.2/ssl.lua' failed
make: *** [out/share/lua/5.2/ssl.lua] Error 1
Traceback (most recent call last):
  File "scripts/module.py", line 281, in <module>
    args.func(args)
  File "scripts/module.py", line 234, in build
    make_modules(modules, args)
  File "scripts/module.py", line 124, in make_modules
    raise Exception('make failed for ' + module.name)
Exception: make failed for lua
scripts/build failed: fs_type=$fs_type jdkbase=$jdkbase ARCH=$arch mode=$mode OSV_BASE=$SRC OSV_BUILD_PATH=$OSV_BUILD_PATH scripts/module.py $j_arg build -c $modules $usrskel_arg $no_required_arg
`

**Comment by nyh** [comment] 2019-01-27 15:35
@Myhat2you please open a new issue, don't piggyback on an unrelated issue. Sadly, as commit af16f934ab795e607e3041dc707dbcd7ea4a7229 explains, because of some LUA dependencies, we require the old openssl 1.0, and can't work with 1.1. Fedora has an option to install the old 1.0 for compatibility, and maybe Ubuntu has too, but I don't know.

Note that if you create an image without the "lua" module - namely, without the "cli", you will not need this old openssl stuff anyway. E.g., "scripts/build image=rogue" will build you an image with just the rogue game, without Lua :-) Eventually someone should rework commit af16f934ab795e607e3041dc707dbcd7ea4a7229 so that things will work on modern openssl as well, and solve this issue - but please open a new issue for that.

**Comment by Myhat2you** [comment] 2019-01-28 09:40
Thanks for the response! I deleted my post after realizing I don't need LUA
and can create the image without it :)

Thanks again
