### ISSUE TITLE
Building in mode=debug (probably) uses bits/alltypes.h from release dir

### ISSUE THREAD

**Issue by Foxlik** [cloudius-systems/osv#659] opened 2015-10-04 21:25 UTC
When building OSv from clean source on Gentoo with mode=debug I get the bits/alltypes.h missing error. When I build mode=release, mode=debug does not fail any more ... 

I hope to get more time later this week to investigate further.

**Comment by nyh** [comment] 2015-10-11 10:10
I cannot reproduce this problem (on Fedora 21) - removing the entire build/ directory and running "make mode=debug" works for me.
Also looking at Makefile, we have
INCLUDES += -isystem $(out)/gen/include
note the $(out) - which is build/debug in debug mode - appears there correctly.

The problem might be different - is it possible we forget the "generated-headers" dependencies on some of the compilations, causing build to fail randomly depending on compilation order, when we compile some file before generating the headers first? I'll take a look to see if I can find such a problem.

Can you please run "make V=1" to see the verbose output of what gets run and see if we can learn something from it?

**Comment by nyh** [comment] 2015-10-11 10:14
There are indeed places we forgot to create these generated headers. For example:

```
$ make build/release.x64/bsd/cddl/contrib/opensolaris/lib/libzfs/common/zfs_prop.o
Building into build/release.x64
  CC bsd/sys/cddl/contrib/opensolaris/common/zfs/zfs_prop.c
In file included from bsd/cddl/compat/opensolaris/include/solaris.h:8:0,
                 from bsd/cddl/contrib/opensolaris/lib/libzpool/common/sys/zfs_context.h:44,
                 from bsd/sys/cddl/contrib/opensolaris/uts/common/fs/zfs/sys/zio.h:31,
                 from bsd/sys/cddl/contrib/opensolaris/common/zfs/zfs_prop.c:29:
include/api/fcntl.h:20:27: fatal error: bits/alltypes.h: No such file or directory
 #include <bits/alltypes.h>
```

If make randomly decided (?) to compile this file first, it will fail...

**Comment by Foxlik** [comment] 2015-10-11 20:33
Unfortunatelly I do have to ask for reopen. After reporting #660 and getting around without ```-j 6```, I still get this error: 

```
root@vulcan:/home/fox/osv# git rev-parse HEAD
5fec7c6d6dfd6e3a5d8fa69c5f64a89dc6469afb
root@vulcan:/home/fox/osv# V=1 scripts/build mode=debug image=cli jdkbase=/home/fox/jdk
Building into build/debug.x64
sh scripts/gen-version-header build/debug.x64/gen/include/osv/version.h
ln -nsf debug.x64 build/debug
ln -nsf debug.x64 build/last
No such image configuration: cli. Assuming list of modules.
Importing /home/fox/osv/modules/cli/module.py
Importing /home/fox/osv/modules/lua/module.py
Importing /home/fox/osv/modules/ncurses/module.py
Importing /home/fox/osv/modules/libedit/module.py
Importing /home/fox/osv/modules/httpserver/module.py
Importing /home/fox/osv/modules/openssl/module.py
No module.py in /home/fox/osv/modules/libz
No module.py in /home/fox/osv/modules/libtools
No module.py in /home/fox/osv/modules/libyaml
Modules:
  lua
  ncurses
  libedit
  libz
  openssl
  libtools
  libyaml
  httpserver.*
  cli.*
make: Nothing to be done for 'module'.
make: Nothing to be done for 'module'.
make: Nothing to be done for 'module'.
mkdir -p obj
mkdir -p obj/stub
mkdir -p obj/json
mkdir -p obj/api
mkdir -p obj/autogen
mkdir -p autogen
make -C osv-gui
make[1]: Entering directory '/home/fox/osv/modules/httpserver/osv-gui'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/fox/osv/modules/httpserver/osv-gui'
g++ -g -Wall -std=c++11 -fPIC -isystem /home/fox/osv/external/x64/misc.bin/usr/include -I/home/fox/osv/build/release/gen/include -I../../include -I. -I../../java -I../../arch/x64 -I../.. -I/home/fox/jdk/include -I/home/fox/jdk/include/linux -O2 -MD -MT obj/api/network.o -MP -c -MMD  -o obj/api/network.o api/network.cc
In file included from ../../tools/ifconfig/network_interface.hh:12:0,
                 from api/network.cc:10:
../../bsd/sys/net/if_data.h:10:27: fatal error: bits/alltypes.h: No such file or directory
 #include <bits/alltypes.h>
                           ^
compilation terminated.
Makefile:86: recipe for target 'obj/api/network.o' failed
make: *** [obj/api/network.o] Error 1
Traceback (most recent call last):
  File "scripts/module.py", line 241, in <module>
    args.func(args)
  File "scripts/module.py", line 198, in build
    make_modules(modules, args)
  File "scripts/module.py", line 102, in make_modules
    raise Exception('make failed for ' + module.name)
Exception: make failed for httpserver
scripts/build failed: jdkbase=$jdkbase ARCH=$arch OSV_BASE=$SRC OSV_BUILD_PATH=$OSV_BUILD_PATH scripts/module.py $j_arg build -c $modules
root@vulcan:/home/fox/osv#
```

If there is more info I can provide, please let me know.

**Comment by Foxlik** [comment] 2015-10-11 20:40
Unfortunatelly I do have to ask for reopen. After reporting #660 and getting around without ```-j 6```, I still get this error: 

```
root@vulcan:/home/fox/osv# git rev-parse HEAD
5fec7c6d6dfd6e3a5d8fa69c5f64a89dc6469afb
root@vulcan:/home/fox/osv# V=1 scripts/build mode=debug image=cli jdkbase=/home/fox/jdk
Building into build/debug.x64
sh scripts/gen-version-header build/debug.x64/gen/include/osv/version.h
ln -nsf debug.x64 build/debug
ln -nsf debug.x64 build/last
No such image configuration: cli. Assuming list of modules.
Importing /home/fox/osv/modules/cli/module.py
Importing /home/fox/osv/modules/lua/module.py
Importing /home/fox/osv/modules/ncurses/module.py
Importing /home/fox/osv/modules/libedit/module.py
Importing /home/fox/osv/modules/httpserver/module.py
Importing /home/fox/osv/modules/openssl/module.py
No module.py in /home/fox/osv/modules/libz
No module.py in /home/fox/osv/modules/libtools
No module.py in /home/fox/osv/modules/libyaml
Modules:
  lua
  ncurses
  libedit
  libz
  openssl
  libtools
  libyaml
  httpserver.*
  cli.*
make: Nothing to be done for 'module'.
make: Nothing to be done for 'module'.
make: Nothing to be done for 'module'.
mkdir -p obj
mkdir -p obj/stub
mkdir -p obj/json
mkdir -p obj/api
mkdir -p obj/autogen
mkdir -p autogen
make -C osv-gui
make[1]: Entering directory '/home/fox/osv/modules/httpserver/osv-gui'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/fox/osv/modules/httpserver/osv-gui'
g++ -g -Wall -std=c++11 -fPIC -isystem /home/fox/osv/external/x64/misc.bin/usr/include -I/home/fox/osv/build/release/gen/include -I../../include -I. -I../../java -I../../arch/x64 -I../.. -I/home/fox/jdk/include -I/home/fox/jdk/include/linux -O2 -MD -MT obj/api/network.o -MP -c -MMD  -o obj/api/network.o api/network.cc
In file included from ../../tools/ifconfig/network_interface.hh:12:0,
                 from api/network.cc:10:
../../bsd/sys/net/if_data.h:10:27: fatal error: bits/alltypes.h: No such file or directory
 #include <bits/alltypes.h>
                           ^
compilation terminated.
Makefile:86: recipe for target 'obj/api/network.o' failed
make: *** [obj/api/network.o] Error 1
Traceback (most recent call last):
  File "scripts/module.py", line 241, in <module>
    args.func(args)
  File "scripts/module.py", line 198, in build
    make_modules(modules, args)
  File "scripts/module.py", line 102, in make_modules
    raise Exception('make failed for ' + module.name)
Exception: make failed for httpserver
scripts/build failed: jdkbase=$jdkbase ARCH=$arch OSV_BASE=$SRC OSV_BUILD_PATH=$OSV_BUILD_PATH scripts/module.py $j_arg build -c $modules
root@vulcan:/home/fox/osv#
```

If there is more info I can provide, please let me know.

**Comment by nyh** [comment] 2015-10-11 20:53
Good catch. It appears that the osv-gui makefile, which is completely separate from OSv's main makefile, and used when you use image=cli, did

g++ -g -Wall -std=c++11 -fPIC -isystem /home/fox/osv/external/x64/misc.bin/usr/include -I/home/fox/osv/build/release/gen/include -I../../include -I. -I../../java -I../../arch/x64 -I../.. -I/home/fox/jdk/include -I/home/fox/jdk/include/linux -O2 -MD -MT obj/api/network.o -MP -c -MMD  -o obj/api/network.o api/network.cc

I.e., that makefile incorrectly used build/release, which isn't correct because you used mode=debug.

So I guess I need to scour that Makefile, and maybe other makefile, for this type of mistake.

**Comment by nyh** [comment] 2015-10-11 21:05
Avi, Pekka, or @Foxlik, can you please "reopen" this bug? Sadly github's annoying bug tracker doesn't let ordinary mortals to reopen issues :-(

**Comment by Foxlik** [comment] 2015-10-11 21:11
@nyh unfortunately, for these things I am a mere mortal as well. Or I have no idea where the button is.

**Comment by avikivity** [comment] 2015-10-12 06:58
The button was -------------------------------------------------------------------------v there

(but now it's marked close)

(please adjust font until arrow actually points at button)

**Comment by nyh** [comment] 2015-10-12 07:29
On Mon, Oct 12, 2015 at 9:58 AM, Avi Kivity <notifications@github.com>
wrote:

> The button was
> -------------------------------------------------------------------------v
> there
>
> (but now it's marked close)
>
> (please adjust font until arrow actually points at button)
>

Avi, with your incredible superpowers you are probably not aware of this,
but on Github's bug tracker, the UI differs depending on your permissions:
* You, as a committer, are allowed both to close open bugs and to reopen
closed bugs, so you see these buttons.
* @Foxlik, as the creator of the bug is allowed to close it (so he sees a
"close" button now), but is apparently not given the superpower of
reopening a bug after it was closed.
* I, a mere mortal who is not the creator of this bug nor a committer, have
neither of these powers - I cannot close an open bug, nor can I reopen a
closed bug - so I don't see these buttons at all.

All of this is very stupid of github: In many projects like ours', the
whole idea of a bug tracker is to let non-committers use it freely. You
don't want non-committers to be able to ruin anything, but any action that
can be undone should have been allowed. This is how other bug trackers,
like Bugzilla, work. It is particularly stupid not to allow a bug's creator
to reopen it, given that he *can* create a new bug with the same text, so
what's the risk in allowing a reopen?

**Comment by avikivity** [comment] 2015-10-12 07:31
Ah, I assumed that being able to close a bug also allows reopening. Silly me.

**Closed** 2015-10-12 08:35 UTC
