### ISSUE TITLE
error with shared library - failed looking up symbol mremap

### ISSUE THREAD

**Issue by hartsantler** [cloudius-systems/osv#697] opened 2015-12-10 19:22 UTC
My application loads another dynamic library, `libcivetweb.so.1` which i added to usr.manifest and it gets included in the image under `/usr/lib`, is this the correct place to put it?  Note myapp.so is in `/tools`

here is the error i am getting when running my image.
```
Adding /tools/myapp.so...
Adding /usr/lib/libcivetweb.so.1...
OSv v0.24-25-gb32e6d9
eth0: 192.168.122.15
/tools/myapp.so: failed looking up symbol mremap

[backtrace]
0x000000000034445d <elf::object::symbol(unsigned int)+205>
0x0000000000395e52 <elf::object::arch_relocate_rela(unsigned int, unsigned int, void*, long)+82>
0x0000000000341393 <elf::object::relocate_rela()+147>
0x0000000000342fc7 <elf::object::relocate()+199>
0x00000000003468b3 <elf::program::load_object(std::string, std::vector<std::string, std::allocator<std::string> >, std::vector<std::shared_ptr<elf::object>, std::allocator<std::shared_ptr<elf::object> > >&)+1635>
0x000000000034712b <elf::program::get_library(std::string, std::vector<std::string, std::allocator<std::string> >)+251>
0x000000000041556a <osv::application::application(std::string const&, std::vector<std::string, std::allocator<std::string> > const&, bool, std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > > const*)+522>
0x0000000000415e55 <osv::application::run(std::string const&, std::vector<std::string, std::allocator<std::string> > const&, bool, std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > > const*)+117>
0x000000000041607b <osv::application::run(std::vector<std::string, std::allocator<std::string> > const&)+27>
0x0000000000212d15 <do_main_thread(void*)+1653>
0x000000000043fec5 <???+4456133>
0x00000000003efad7 <thread_main_c+39>
0x0000000000391fb5 <???+3743669>
```

**Comment by nyh** [comment] 2015-12-13 11:07
@hartsantler, /usr/lib is a good place - it is on OSv's default shared-library search path ("/" is also on this search path).
The missing mremap() is a duplicate of issue #184.
In that issue, @penberg offered a patch. @penberg, do you remember why we never committed this patch? @hartsantler, you can perhaps take that patch from #184 and see if it works for you.

**Closed by nyh** 2015-12-13 11:07 UTC

**Comment by penberg** [comment] 2015-12-14 07:03
@nyh The ``mremap()`` implementation I submitted was not complete and IIRC you found some issues that I didn't have time to address in your review. It's probably a decent starting point for completing the work, though.
