### ISSUE TITLE
how to use jdk8

### ISSUE THREAD

**Issue by yuwang888** [cloudius-systems/osv#935] opened 2018-01-10 12:35 UTC
i want to know how to use jdk8 with scripts/build and run.py method
#cat module.py 

from osv.modules import api
api.require('java')
...
but it default used jdk7

i know using captanfile base: cloudius/osv-openjdk8
but i want to use module.py

**Comment by nyh** [comment] 2018-01-10 23:27
This is not a bug report, next time please write such questions on the osv mailing list (osv-dev@googlegroups.com), not on the bug tracker. I'm closing this issue, but still answering you here:

You can specify on the scripts/build command line a different module which "provides" the "java" name (which your module.py "requires"). For example,

```
scripts/build image=openjdk8-fedora,cassandra
```
The "openjdk8-fedora" fetches the latest precompiled version of openjdk8 from Fedora's repositories (you don't need to be using Fedora yourself), and uses that. The openjdk8-fedora module "provides" the "java" feature which the cassandra module (and your own module) "require".

We also have several other openjdk8 implementations in our apps/ directory. For example, this also works:
```
scripts/build image=openjdk8-zulu-full,cassandra
``` 
This fetches another variant of Java 8, from Azul.

We have many other variants - also "compact" versions of Java (for smaller images), versions without our "isolation" feature attempting to allow multiple Java programs to run in isolation, and more. If you're interested, let's continue this discussion on the mailing list. Good luck.

**Closed by nyh** 2018-01-10 23:27 UTC
