### ISSUE TITLE
Got some trouble when running memcached image

### ISSUE THREAD

**Issue by Answerhua** [cloudius-systems/osv#928] opened 2017-11-17 12:19 UTC
I try:
sudo `scripts/build image=memcached`
in ubuntu

But it shows some errors:
`No such image configuration: memcached. Assuming list of modules.
Importing /home/wande/osv/apps/memcached/module.py
Modules:
  memcached.*
cc -pie -o memcached -std=gnu99 -fpie -rdynamic -DHAVE_CONFIG_H  src/assoc.c src/cache.c src/daemon.c src/hash.c src/items.c src/memcached.c src/slabs.c src/stats.c src/thread.c src/util.c src/jenkins_hash.c src/murmur3_hash.c -levent -lpthread
cc: error: src/assoc.c: No such file or directory
cc: error: src/cache.c: No such file or directory
cc: error: src/daemon.c: No such file or directory
cc: error: src/hash.c: No such file or directory
cc: error: src/items.c: No such file or directory
cc: error: src/memcached.c: No such file or directory
cc: error: src/slabs.c: No such file or directory
cc: error: src/stats.c: No such file or directory
cc: error: src/thread.c: No such file or directory
cc: error: src/util.c: No such file or directory
cc: error: src/jenkins_hash.c: No such file or directory
cc: error: src/murmur3_hash.c: No such file or directory
Makefile:22: recipe for target 'memcached' failed
make: *** [memcached] Error 1
Traceback (most recent call last):
  File "scripts/module.py", line 281, in <module>
    args.func(args)
  File "scripts/module.py", line 234, in build
    make_modules(modules, args)
  File "scripts/module.py", line 124, in make_modules
    raise Exception('make failed for ' + module.name)
Exception: make failed for memcached

I don't know whether it is because osv doesn't support memcached image any more.

**Comment by nyh** [comment] 2017-11-19 12:34
I can reproduce the same error.
On my machine, the first attempt at compilation brings
```
checking for libevent directory... configure: error: libevent is required.  You can get it from http://www.monkey.org/~provos/libevent/

      If it's already installed, specify its path using --with-libevent=/dir/

Makefile:10: recipe for target 'src' failed
``` 
And the second brings the messages you saw:
```
cc -pie -o memcached -std=gnu99 -fpie -rdynamic -DHAVE_CONFIG_H  src/assoc.c src/cache.c src/daemon.c src/hash.c src/items.c src/memcached.c src/slabs.c src/stats.c src/thread.c src/util.c src/jenkins_hash.c src/murmur3_hash.c -levent -lpthread
cc: error: src/assoc.c: No such file or directory
cc: error: src/cache.c: No such file or directory
cc: error: src/daemon.c: No such file or directory
cc: error: src/hash.c: No such file or directory
cc: error: src/items.c: No such file or directory
cc: error: src/memcached.c: No such file or directory
cc: error: src/slabs.c: No such file or directory
cc: error: src/stats.c: No such file or directory
cc: error: src/thread.c: No such file or directory
cc: error: src/util.c: No such file or directory
cc: error: src/jenkins_hash.c: No such file or directory
cc: error: src/murmur3_hash.c: No such file or directory
Makefile:22: recipe for target 'memcached' failed
```
You probably need to install the libevent-devel (or similar) package so that libevent is found. But the second issue (the second "make" fails differently) is indeed annoying and needs to be fixed.
There are two issues here:
1. Why do we need this

**Comment by nyh** [comment] 2017-11-19 12:41
Fixed by apps.git/d9c0bb2471430f624a06962d095e0726e5ea5c49

**Comment by nyh** [comment] 2017-11-19 12:45
By the way, in Fedora "dnf install libevent-devel" indeed fixed the missing libdevel problem.

But sadly, memcached doesn't actually work, because of issue #689.

This issue is actually easy to work around by switching the Makefile to link the executable as "-shared" instead of "-pie". See issue #689.

**Comment by Answerhua** [comment] 2017-11-20 12:47
@nyh I am really sorry to bother you again. 
I have updated the Submodule, and install libevent.
But when I run
`sudo scripts/build image=memcached`

There are still some errors.
`OSv v0.24-467-gd52cb12
eth0: 192.168.122.15
Running mkfs...
Adding /libenviron.so...
Adding /zpool.so...
Adding /libzfs.so...
Adding /libuutil.so...
Adding /zfs.so...
Adding /tools/mkfs.so...
Adding /tools/cpiod.so...
Adding /tools/mount-nfs.so...
Adding /tools/umount.so...
Adding /usr/lib/libgcc_s.so.1...
Adding /etc/hosts...
Link /etc/mnttab to /proc/mounts ...
Adding /etc/fstab...
Adding /dev...
Adding /proc...
Adding /tmp...
Adding /memcached...

ERROR: file upload failed:
[Errno 2] No such file or directory: 'not'
scripts/build failed: $SRC/scripts/upload_manifest.py -o usr.img -m usr.manifest -D jdkbase=$jdkbase -D gccbase=$gccbase -D glibcbase=$glibcbase -D miscbase=$miscbase
`

I don't know whether I made some mistakes.

**Comment by nyh** [comment] 2017-11-20 19:32
Can you please look at build/last/usr.manifest, does it have a line with the word "not"?
My guess is that apps/memcached/Makefile had some problem running "ldd" but I don't know why...
Can you please try "cd apps/memcached; make clean" before trying to build again?

**Comment by Answerhua** [comment] 2017-11-21 10:19
Thank you very much. Following your advice, I try
`cat build/last/usr.manifest`
It shows me
`/libevent-2.1.so.6: not`
So I guess it is the problem of libevent.

Then I link libevent to /usr/lib by:
`sudo ln -s /usr/libevent/lib/libevent-2.1.so.6 /usr/lib/libevent-2.1.so.6`

Finally, it worked.
`wande@ubuntu:~/osv$ sudo scripts/run.py -e "memcached -u root"
OSv v0.24-467-gd52cb12
eth0: 192.168.122.15
Memcached for OSV, based on Memcached 1.4.21
`

However, I don't know how to use it.  I try `telnet 127.0.0.1 11211`  like what I do in normal memcached,
but the screen displays nothing. I can neither set nor get.

Would you please tell me how to use it. Thanks again.

**Comment by nyh** [comment] 2017-11-21 12:25
I see. So the "ldd" tool couldn't find libevent-2.1.so.6, and the scripts in apps/memcached/Makefile wrongly used the error message as a silly file name. The latter problem should be fixed (a patch is welcome!), of course, but I'm also curious how ldd couldn't find the library, but "-levent" during the compilation did. What Linux distribution are you using?
Please ask the usage questions on the OSv mailing list, and I'll answer there.

**Comment by Answerhua** [comment] 2017-11-22 00:12
I am using Ubuntu 16.04

**Comment by Answerhua** [comment] 2017-11-22 00:15
I will ask on the mailing list, thank you very much.

**Comment by nyh** [comment] 2017-11-23 10:52
@answerhua, did you do anything special to get the libevent library to be placed in /usr/libevent, where ldd didn't find it?
As far as I can tell from searching the web, Ubuntu 16.04 did not have libevent 2.1.so.6 (see https://packages.ubuntu.com/xenial-updates/amd64/libevent-2.0-5/filelist),   and those that did have it, have it in a different directory - see https://packages.ubuntu.com/artful/amd64/libevent-2.1-6/filelist 
So I don't know what I'm missing.

**Closed by nyh** 2017-11-23 10:52 UTC

**Comment by Answerhua** [comment] 2017-11-24 00:53
@nyh. Hello, I installed libevent source code from a website and then compiled it. After that I placed it to /usr/libevent.
