### ISSUE TITLE
Assertion failed, crash

### ISSUE THREAD

**Issue by chrisbetz** [cloudius-systems/osv#696] opened 2015-12-10 12:47 UTC
Hi,

I'm trying to run latest riemann on OSv (for sake of evaluating OSv and having a unikernel-based logmon solution). From time to time things go badly wrong like this:

Assertion failed. ttp->get_statell) o>c 1 (assd/sys/nlet",net/tcp_input.cc: tcp_do_segm ent:  1s076)

[backtracee]
rvice "r0x0000000000227898 <__assert_fail+24>
i0x0000000000278223 <???+2589219>
0x000000000027979c <???+2594716>
0x000000000041a3ae <net_channel::process_queue()+94>
0x00000000002377bf <int sbwait_tmo<osv::clock::uptime>(socket_, sockbuf_, boost::optional<std::chrono::time_point<osv::clock::uptime, osv::clock::uptime::duration> >)+335>
0x0000000000237625 <sbwait+37>
0x000000000023c144 <soreceive_generic+3732>
0x000000000023e96d <kern_recvit+269>
0x000000000023ecbb <sys_recvfrom+251>
0x000000000024e498 <linux_recv+56>
0x000000000023fca1 <recv+17>
0x000010000840f45c <???+138474588>
0x000010000840ed6f <Java_java_net_SocketInputStream_socketRead0+159>
0x000020000061675a <???+6383450>
0x0000200001340133 <???+20185395>
0x00002000006073cf <???+6321103>
0x000020000122dc93 <???+19061907>
0x000020000060770f <???+6321935>
0x000020000060770f <???+6321935>
0x00002000006077e3 <???+6322147>
0x000020000060770f <???+6321935>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x000020000060770f <???+6321935>
0x000020000060770f <???+6321935>
0x000020000060770f <???+6321935>
0x00002000006077e3 <???+6322147>
0x000020000060770f <???+6321935>
0x000020000060770f <???+6321935>
0x000020000060770f <???+6321935>
0x00002000008d5873 <???+9263219>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000010e3703 <???+17708803>

Or like this:
Assertion failed: tp->get_state() > 1 (bsd/sys/netinet/tcp_input.cc: tcp_do_segment: 1076)

[backtrace]
0x0000000000227898 <__assert_fail+24>
0x0000000000278223 <???+2589219>
0x000000000027979c <???+2594716>
0x000000000041a3ae <net_channel::process_queue()+94>
0x0000000000238648 <soclose+152>
0x0000000000431db5 <fdrop+101>
0x0000000000431f6f <fdset(int, file*)+111>
0x000000000042ea79 <dup3+73>
0x000010000840f2c1 <???+138474177>
0x000020000061675a <???+6383450>
0x000020000060798c <???+6322572>
0x000020000060798c <???+6322572>
0x000020000060798c <???+6322572>
0x000020000060798c <???+6322572>
0x000020000060798c <???+6322572>
0x000020000060798c <???+6322572>
0x00002000006079d1 <???+6322641>
0x00002000006079d1 <???+6322641>
0x000020000060798c <???+6322572>
0x000020000060770f <???+6321935>
0x000020000060770f <???+6321935>
0x00002000006077e3 <???+6322147>
0x000020000060770f <???+6321935>
0x000020000060770f <???+6321935>
0x000020000060770f <???+6321935>
0x000020000072cef3 <???+7524083>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000006077e3 <???+6322147>
0x00002000010c9bc3 <???+17603523>

You can find my riemann.osv project on https://github.com/chrisbetz/riemann.osv/ and I'm running on VirtualBox on OS X at the moment.

Would love to see this fixed, as OSv is great otherwise. Thanks for all the work put into that.

Cheers,

Chris

**Comment by wkozaczuk** [comment] 2024-01-27 16:16
Based on this part in both stack traces:
```
Assertion failed: tp->get_state() > 1 (bsd/sys/netinet/tcp_input.cc: tcp_do_segment: 1076)
```
it looks like a duplicate of #454

**Closed by wkozaczuk** 2024-01-27 16:16 UTC
Labels: bug, TCP
