### ISSUE TITLE
OSv crashes when idle

### ISSUE THREAD

**Issue by rowlandwatkins** [cloudius-systems/osv#944] opened 2018-02-06 03:01 UTC
Hi folks,

Got an interesting stack trace after leaving an idle VM running over night:
OSv version: OSv v0.24-472-gf240a59
dependencies: cloud-init, openjdk8-zulu-full

Stack trace:
[[[
15165529985890 < 15204184227830, now=15165530140950

[backtrace]
0x00000000003f117b <sched::timer_list::fired()+1131>
0x00000000003971c6 <interrupt_descriptor_table::invoke_interrupt(unsigned int)+166>
0x00000000003972fa <interrupt+106>
0x000000000039597c <???+3758460>
0x00000000003f3cc7 <sched::cpu::idle()+39>
0x00000000003f3cee <???+4144366>
0x00000000003f5477 <thread_main_c+39>
0x00000000003959a5 <???+3758501>
0xfffffffffffff87f <???+-1921>
0xffff900001320fff <???+20058111>
]]]

Timer problem? I recall something similar a while back, but not sure if the same.

Cheers,

Rowland

**Comment by wkozaczuk** [comment] 2018-02-06 04:29
Is this a duplicate of #382?

**Comment by nyh** [comment] 2018-02-06 22:25
Is, it is indeed a duplicate - note how 15204184227830 - 15165529985890 = 38.65 seconds, i.e. 9 * 2^32 nanoseconds - exactly like in that bug. Sadly, we still have no clue what is causing that bug.

**Closed by nyh** 2018-02-06 22:25 UTC

**Comment by nyh** [comment] 2018-02-08 08:24
@rowlandwatkins was this run over KVM? (I want to know which clock was used).

**Comment by wkozaczuk** [comment] 2018-02-08 13:06
I think it is specific to QEMU. If I remember correctly the crash I saw was on my laptop running either ubuntu natively or Linux in VirtualBox on OSX. I have never seen anything like this on EC2 nor VMware. I have had OSv instance running on AWS for longer than a year. 

Waldek

**Comment by rowlandwatkins** [comment] 2018-02-08 13:29
@nyh no, just using QEMU, I can't say for sure but I don't think I've seen this happen on EC2. I saw some clock skew issues with my main VM, but I'm not sure if that's related. 

In a separate issue, I'm actually trying to get KVM to work with little success...

**Comment by nyh** [comment] 2018-02-08 14:38
Oh, so it's QEMU without KVM?  If that is the case, it's using the HPET clock.

**Comment by nyh** [comment] 2018-02-08 15:21
Here are some wild guesses:

Since commit 778394c31c3fc87fef9ad80eac59cc2e69b9d570 we used 8-byte reads from HPET.
But in QEMU's hw/timer/hpet.c it seems to me (but I'm not sure I'm understanding this correctly) that only 4-byte reads are supported at a time (max_access_size = 4). I think this is a QEMU bug because the HPET specification says that 64-bit reads (which are 64-bit aligned) are allowed.
I wonder if it's possible that we reading the low order bits first, seeing 2^32-1, and then reading the high-order bits and seeing it after it already increased by 1! If that happens, we - temporarily - see time ahead of the real time. However, I don't understand why it would be 9*2^32 nanoseconds (38.65 seconds)... I would have guessed that if the default hpet tick is 10ns, then it should be 10*2^32 nanoseconds (42 seconds) off, not 9... I'm still baffled.
