### ISSUE TITLE
rt_tests report error because of not support sched_getscheduler

### ISSUE THREAD

**Issue by wuqixuan** [cloudius-systems/osv#996] opened 2018-09-08 11:01 UTC
[root@izuf65nf8wcjt73srsaudaz osv]# ./scripts/run.py
OSv v0.51.0-30-g161b4a1
eth0: 192.168.122.15
/tools/cyclictest.so: failed looking up symbol sched_getscheduler

[backtrace]
0x000000000034c5fb <elf::object::symbol(unsigned int, bool)+395>
0x000000000034c6f2 <elf::object::resolve_pltgot(unsigned int)+130>
0x000000000034c8d6 <elf_resolve_pltgot+54>
0x000000000039896e <???+3770734>
0x000010000140aa0f <???+21015055>
0x000010000140710c <main+82>
0x0000000000423e30 <osv::application::run_main()+64>
0x000000000020c5d0 <osv::application::main()+128>
0x0000000000424008 <???+4341768>
0x0000000000455575 <???+4543861>
0x00000000003fb5f7 <thread_main_c+39>
0x0000000000399cb2 <???+3775666>
0x2aa7200a60631fff <???+1617108991>
0x00000000003facff <???+4173055>
0xfb89485354415540 <???+1413567808>

**Comment by nyh** [comment] 2018-09-09 08:58
This is a duplicate of #386. We need to add a sched_getscheduler() minimal implementation to support the normal SCHED_OTHER. I also have patches (not yet committed for support for SCHED_FIFO, if anyone is interested.

**Closed by nyh** 2018-09-09 08:58 UTC
